// Skill roadmaps + athlete guide. Sources: Overcoming Gravity, r/bodyweightfitness, FitnessFAQs, ISSN position stands.
const SKILL_TREES = [
  { key: 'front_lever', name: 'Front lever', family: 'pull',
    why: 'Builds straight-arm lat, scapular depression and anterior core strength that carries into every pull skill.',
    prereq: '12+ strict pull-ups and a 20 s hollow-body hang.',
    steps: [
      { id: 'fl_adv_tuck', name: 'Advanced tuck front lever', type: 'time', goal: '3x15 s', target: { sets: 3, value: 15 },
        how: 'Flat back, hips level with shoulders, arms locked. Depress and retract scapulae.',
        drills: ['Tuck FL raises 3x8', 'Scapular pull-ups 3x10'] },
      { id: 'fl_one_leg', name: 'One-leg front lever', type: 'time', goal: '3x10 s each leg', target: { sets: 3, value: 10 },
        how: 'Extended leg in line with torso, bent knee tucked. Squeeze glutes, no hip pike.',
        drills: ['Adv tuck FL rows 3x6', 'Hanging leg raises 3x10'] },
      { id: 'fl_straddle', name: 'Straddle front lever', type: 'time', goal: '3x8 s clean', target: { sets: 3, value: 8 },
        how: 'Wide straddle, posterior pelvic tilt, body horizontal. Hold only while form is perfect.',
        drills: ['Straddle FL negatives 4x3', 'Band-assisted straddle holds 3x15 s'] },
      { id: 'fl_half_lay', name: 'Half-lay front lever', type: 'time', goal: '3x6 s', target: { sets: 3, value: 6 },
        how: 'Legs together, knees bent 90 deg at hips line. Keep hips from dropping.',
        drills: ['Straddle FL raises 4x3', 'Weighted pull-ups 4x5'] },
      { id: 'fl_full', name: 'Full front lever', type: 'time', goal: '3x5 s', target: { sets: 3, value: 5 },
        how: 'Legs together, toes pointed, ribs down. Shoulders to ankles one straight line.',
        drills: ['Full FL negatives 5x2', 'Band-assisted full FL 3x10 s'] },
      { id: 'fl_full_long', name: 'Full front lever (long hold)', type: 'time', goal: '3x10 s', target: { sets: 3, value: 10 },
        how: 'Same line, slower breathing. Stop the set at first hip drop.',
        drills: ['Full FL 5x5 s cluster', 'Ice cream makers 3x5'] },
      { id: 'fl_pullups', name: 'Front lever pull-ups (touch)', type: 'reps', goal: '3x3 reps', target: { sets: 3, value: 3 },
        how: 'Pull bar to hips staying horizontal; lower with control to full lever.',
        drills: ['Straddle FL pull-ups 4x3', 'FL row eccentrics 3x3'] }
    ] },

  { key: 'planche', name: 'Planche', family: 'push',
    why: 'Develops straight-arm pushing strength, protracted scapulae and the elbow tendons needed for elite push skills.',
    prereq: '20+ dips, solid wrist prep and 60 s pseudo planche lean.',
    steps: [
      { id: 'pl_lean', name: 'Planche lean', type: 'time', goal: '3x30 s, shoulders past wrists', target: { sets: 3, value: 30 },
        how: 'Locked elbows, protract hard, posterior pelvic tilt. Lean until shoulders are well past hands.',
        drills: ['Wrist push-ups 2x10', 'Scapular push-ups 3x12'] },
      { id: 'pl_tuck', name: 'Tuck planche', type: 'time', goal: '3x20 s', target: { sets: 3, value: 20 },
        how: 'Round the upper back, knees to chest, hips at shoulder height.',
        drills: ['PPPU 3x10', 'Tuck planche shrugs 3x8'] },
      { id: 'pl_adv_tuck', name: 'Advanced tuck planche', type: 'time', goal: '3x15 s', target: { sets: 3, value: 15 },
        how: 'Flat back, hips level with shoulders, knees under hips.',
        drills: ['Adv tuck planche push-ups 3x5', 'Lean holds with band 3x20 s'] },
      { id: 'pl_straddle', name: 'Straddle planche', type: 'time', goal: '3x10 s clean', target: { sets: 3, value: 10 },
        how: 'Wide straddle, locked elbows, body horizontal. Protract and push the floor away.',
        drills: ['Straddle planche presses from tuck 3x3', 'Weighted dips 4x5'] },
      { id: 'pl_half_lay', name: 'Half-lay planche', type: 'time', goal: '3x8 s', target: { sets: 3, value: 8 },
        how: 'Legs together, hips extended, knees bent. Bridge between straddle and full.',
        drills: ['Narrow straddle holds 4x6 s', 'Band-assisted full planche 3x10 s'] },
      { id: 'pl_full', name: 'Full planche', type: 'time', goal: '3x5 s clean', target: { sets: 3, value: 5 },
        how: 'Legs together, glutes tight, hips at shoulder height, no pike or arch.',
        drills: ['Full planche negatives from HS 4x2', 'Planche leans with ankle weights 3x15 s'] },
      { id: 'pl_full_long', name: 'Full planche (long hold)', type: 'time', goal: '3x10 s', target: { sets: 3, value: 10 },
        how: 'Hold perfect line under fatigue; stop the set at the first hip drop.',
        drills: ['Full planche 6x3 s clusters', 'Maltese leans (rings) 3x10 s'] },
      { id: 'pl_pushups', name: 'Full planche push-ups', type: 'reps', goal: '3x3 reps', target: { sets: 3, value: 3 },
        how: 'Lower to chest near hands while keeping body horizontal; lock out fully each rep.',
        drills: ['Straddle planche push-ups 4x3', 'Full PPU eccentrics 3x2'] }
    ] },

  { key: 'hspu', name: 'Handstand push-up', family: 'push',
    why: 'Builds vertical pressing power and overhead stability for freestanding HSPU and 90 degree push-ups.',
    prereq: 'Freestanding handstand 30 s and 15 pike push-ups.',
    steps: [
      { id: 'hspu_pike_elev', name: 'Elevated pike push-up', type: 'reps', goal: '3x10, feet on box', target: { sets: 3, value: 10 },
        how: 'Hips over hands, head travels to a tripod in front of hands, elbows at 45 deg.',
        drills: ['Pike push-up negatives 3x5', 'Overhead press 3x8'] },
      { id: 'hspu_wall_neg', name: 'Wall HSPU negatives', type: 'reps', goal: '3x5 slow (4 s down)', target: { sets: 3, value: 5 },
        how: 'Chest to wall or back to wall, tripod head position, controlled lowering.',
        drills: ['Wall HS shoulder taps 3x10', 'Partial wall HSPU 3x6'] },
      { id: 'hspu_wall', name: 'Wall HSPU (full ROM)', type: 'reps', goal: '3x6', target: { sets: 3, value: 6 },
        how: 'Head touches floor or mat, full lockout with shrug at top, no kipping.',
        drills: ['Wall HSPU clusters 6x2', 'Pike push-ups 3x12'] },
      { id: 'hspu_deficit', name: 'Deficit wall HSPU', type: 'reps', goal: '3x5 on parallettes', target: { sets: 3, value: 5 },
        how: 'Head goes below hand level, elbows track forward. Keep a hollow body.',
        drills: ['Deficit negatives 3x3', 'Weighted dips 3x6'] },
      { id: 'hspu_free_neg', name: 'Freestanding HSPU negatives', type: 'reps', goal: '3x3 controlled', target: { sets: 3, value: 3 },
        how: 'Balance with fingers while lowering; keep hips stacked, slight lean forward.',
        drills: ['Freestanding HS 5x30 s', 'Wall HSPU with toes only 3x4'] },
      { id: 'hspu_free', name: 'Freestanding HSPU', type: 'reps', goal: '3x3', target: { sets: 3, value: 3 },
        how: 'Lower and press while balancing; small tripod, push away from floor at top.',
        drills: ['Partial freestanding HSPU 3x4', 'Deficit wall HSPU 3x6'] },
      { id: 'hspu_90_neg', name: '90 deg push-up negative', type: 'reps', goal: '3x3 to planche position', target: { sets: 3, value: 3 },
        how: 'From handstand, lower into a bent-arm planche shape, hips stay high.',
        drills: ['Tuck 90 deg holds 3x10 s', 'Bent-arm planche holds 3x8 s'] },
      { id: 'hspu_90', name: '90 deg push-up (tuck to straddle)', type: 'reps', goal: '3x2 full reps', target: { sets: 3, value: 2 },
        how: 'Lower to 90 deg hold, lean forward, press back to handstand without kicking.',
        drills: ['Tuck 90 deg push-ups 3x3', 'Band-assisted 90 deg push-ups 3x3'] }
    ] },

  { key: 'oahs_press', name: 'Press to handstand and one-arm handstand', family: 'balance',
    why: 'Turns a freestanding handstand into strength-based balance: compression presses and single-arm control.',
    prereq: 'Freestanding handstand 45 s and pancake/pike mobility.',
    steps: [
      { id: 'oa_hs60', name: 'Freestanding handstand 60 s', type: 'time', goal: '3x60 s', target: { sets: 3, value: 60 },
        how: 'Open shoulders, stacked hips, finger-pressure balance only.',
        drills: ['Wall HS line drills 3x45 s', 'Pike compression lifts 3x10'] },
      { id: 'oa_straddle_press_wall', name: 'Straddle press (feet on box or wall)', type: 'reps', goal: '3x5', target: { sets: 3, value: 5 },
        how: 'Shoulders lean forward over hands, compress, lift hips first then legs.',
        drills: ['Elevated straddle press 3x5', 'Seated pancake leg lifts 3x10'] },
      { id: 'oa_straddle_press', name: 'Straddle press to handstand', type: 'reps', goal: '3x3 freestanding', target: { sets: 3, value: 3 },
        how: 'Start from straddle L or stand, lean, float legs up without jumping.',
        drills: ['Press negatives 3x3', 'Straddle L-sit 3x10 s'] },
      { id: 'oa_pike_press', name: 'Pike press to handstand', type: 'reps', goal: '3x3', target: { sets: 3, value: 3 },
        how: 'Legs together and straight, deep compression, shoulders well forward.',
        drills: ['Pike press negatives 3x3', 'Pike compression pulses 3x15'] },
      { id: 'oa_straddle_hs', name: 'Straddle handstand weight shift', type: 'time', goal: '5x10 s on fingertips of one hand', target: { sets: 5, value: 10 },
        how: 'Wide straddle, shift hips over one hand, other hand touches lightly.',
        drills: ['Shoulder taps in HS 3x10', 'Wall side-facing OAHS 4x20 s'] },
      { id: 'oa_oahs_wall', name: 'OAHS against wall (side)', type: 'time', goal: '3x30 s each arm', target: { sets: 3, value: 30 },
        how: 'Hip and shoulder line stacked over working hand, lat engaged, fist or fingers press.',
        drills: ['Flag position holds 3x15 s', 'Wrist strengthening 2x15'] },
      { id: 'oa_oahs_free', name: 'Freestanding OAHS (straddle)', type: 'time', goal: '5x5 s each arm', target: { sets: 5, value: 5 },
        how: 'Enter from straddle HS, release slowly, steer with fingers and hip.',
        drills: ['OAHS attempts 10x1 per arm', 'Two-arm HS narrow hands 3x30 s'] },
      { id: 'oa_oahs_long', name: 'Freestanding OAHS 15 s', type: 'time', goal: '3x15 s each arm', target: { sets: 3, value: 15 },
        how: 'Consistent entries, legs may close gradually once stable.',
        drills: ['Daily 10-min OAHS practice', 'Straddle-to-legs-together transitions 3x3'] }
    ] },

  { key: 'back_lever', name: 'Back lever to German hang and maltese prep', family: 'pull',
    why: 'Builds biceps tendon and shoulder extension capacity, the base for ring strength such as maltese and Hefesto.',
    prereq: 'Pain-free German hang 30 s and skin-the-cat 3x5.',
    steps: [
      { id: 'bl_straddle', name: 'Straddle back lever', type: 'time', goal: '3x15 s', target: { sets: 3, value: 15 },
        how: 'Straight arms, chest down, hips extended, slight shoulder protraction.',
        drills: ['Skin-the-cat 3x5', 'German hang 3x30 s'] },
      { id: 'bl_full', name: 'Full back lever', type: 'time', goal: '3x10 s', target: { sets: 3, value: 10 },
        how: 'Legs together, glutes squeezed, body horizontal. Do not bend elbows.',
        drills: ['BL negatives from inverted hang 3x3', 'Supinated straight-arm curls 3x8'] },
      { id: 'bl_full_long', name: 'Full back lever 20 s', type: 'time', goal: '3x20 s', target: { sets: 3, value: 20 },
        how: 'Rings slightly turned out; keep arms locked under fatigue.',
        drills: ['BL to German hang transitions 3x3', 'Ring support hold turned out 3x30 s'] },
      { id: 'bl_pullouts', name: 'Back lever pull-outs', type: 'reps', goal: '3x3 (German hang to BL to inverted)', target: { sets: 3, value: 3 },
        how: 'Pull from German hang through BL to inverted hang with straight arms.',
        drills: ['Slow skin-the-cats 3x5', 'Straight-arm lat pulldowns behind 3x8'] },
      { id: 'bl_maltese_lean', name: 'Maltese lean (rings or floor)', type: 'time', goal: '3x15 s, hands at hip level', target: { sets: 3, value: 15 },
        how: 'Hands wide and low, lean forward hard, depress and protract.',
        drills: ['Band-assisted maltese 3x10 s', 'Wide straddle planche 3x6 s'] },
      { id: 'bl_iron_prep', name: 'Iron cross prep (band-assisted)', type: 'time', goal: '3x10 s with light band', target: { sets: 3, value: 10 },
        how: 'Only after 6+ months of ring support work. Arms straight, rings turned out, stop at any elbow pain.',
        drills: ['Ring flyes on knees 3x8', 'Cross pulls on cables 3x10'] }
    ] },

  { key: 'hefesto', name: 'Hefesto (optional)', family: 'pull',
    why: 'Bent-arm pull from back lever / German hang to support; extreme elbow and biceps strength.',
    prereq: 'Full back lever 3x10 s, German hang 60 s, 20+ pull-ups, no elbow pain.',
    steps: [
      { id: 'hf_german_hang', name: 'Deep German hang', type: 'time', goal: '3x45 s relaxed', target: { sets: 3, value: 45 },
        how: 'Feet supported early, shoulders fully extended, no elbow bend.',
        drills: ['Assisted German hang 3x30 s', 'Wrist flexor work 2x15'] },
      { id: 'hf_feet_assist', name: 'Feet-assisted Hefesto', type: 'reps', goal: '3x5', target: { sets: 3, value: 5 },
        how: 'Feet on box, bend elbows and pull chest over bar behind you.',
        drills: ['Reverse grip rows 3x10', 'Bicep curls heavy 3x8'] },
      { id: 'hf_negative', name: 'Hefesto negatives', type: 'reps', goal: '3x3 (5 s down)', target: { sets: 3, value: 3 },
        how: 'From support behind bar, lower slowly to German hang.',
        drills: ['Back lever pull-outs 3x3', 'Skin-the-cat 3x5'] },
      { id: 'hf_tuck', name: 'Tuck Hefesto', type: 'reps', goal: '3x2', target: { sets: 3, value: 2 },
        how: 'Tucked legs reduce lever, pull from German hang to support.',
        drills: ['Band-assisted Hefesto 3x3', 'Weighted chin-ups 4x5'] },
      { id: 'hf_full', name: 'Full Hefesto', type: 'reps', goal: '3x1 clean', target: { sets: 3, value: 1 },
        how: 'Straight body, controlled pull, no swing. Stop on any medial elbow pain.',
        drills: ['Tuck Hefesto 3x3', 'Eccentric curls 3x5'] }
    ] },

  { key: 'one_arm_pullup', name: 'One-arm pull-up', family: 'pull',
    why: 'Max unilateral pulling strength; strongly transfers to front lever pulls and muscle-up power.',
    prereq: '15 strict pull-ups and +40% bodyweight weighted pull-up.',
    steps: [
      { id: 'oap_weighted', name: 'Typewriter pull-up', type: 'reps', goal: '3x5 each side', target: { sets: 3, value: 5 },
          how: 'Pull to the bar, slide across to each hand keeping the chin over the bar.',
          drills: ['L-sit pull-ups 3x8', 'Dead hang 3x30 s'] },
      { id: 'oap_archer', name: 'Archer pull-up', type: 'reps', goal: '3x5 each side', target: { sets: 3, value: 5 },
        how: 'Assisting arm stays straight, pull toward working hand.',
        drills: ['Typewriter pull-ups 3x4', 'One-arm hangs 3x20 s'] },
      { id: 'oap_hold', name: 'One-arm flexed hang', type: 'time', goal: '3x10 s each arm (chin over bar)', target: { sets: 3, value: 10 },
        how: 'Pull up with two arms, release one, hold chin above bar with scapula down.',
        drills: ['One-arm scap pulls 3x8', 'Uneven grip pull-ups 3x5'] },
      { id: 'oap_negative', name: 'One-arm negatives', type: 'reps', goal: '3x3 (5 s down) each arm', target: { sets: 3, value: 3 },
        how: 'Slow controlled lowering through full range, resist hard at the bottom.',
        drills: ['Weighted pull-up +35 kg 4x3', 'Isometric holds at 90 deg 3x10 s'] },
      { id: 'oap_assisted', name: 'Band or finger-assisted OAP', type: 'reps', goal: '3x3 with 1 finger/towel assist', target: { sets: 3, value: 3 },
        how: 'Minimal assistance from other hand on towel or wrist.',
        drills: ['Pulley-assisted OAP 3x4', 'Archer pull-ups 3x6'] },
      { id: 'oap_single', name: 'One-arm pull-up', type: 'reps', goal: '1 clean rep each arm', target: { sets: 1, value: 1 },
        how: 'Start from dead hang, slight body turn allowed, chin clears bar.',
        drills: ['Negatives 3x2', 'Weighted pull-up +40% BW 5x2'] },
      { id: 'oap_reps', name: 'One-arm pull-up reps', type: 'reps', goal: '3x2 each arm', target: { sets: 3, value: 2 },
        how: 'Clean reps, no kip, controlled descent.',
        drills: ['OAP clusters 5x1', 'One-arm chin variations 3x2'] }
    ] },

  { key: 'muscle_up_adv', name: 'Muscle-up advanced', family: 'dynamic',
    why: 'Turns pulling power into explosive transitions, a staple of freestyle and competition routines.',
    prereq: '6+ clean kipping-free bar muscle-ups and 20 straight bar dips.',
    steps: [
      { id: 'mu_clean', name: 'Clean bar muscle-ups', type: 'reps', goal: '3x8', target: { sets: 3, value: 8 },
        how: 'Minimal kip, both arms turn over together, full lockout on top.',
        drills: ['Chest-to-bar pull-ups 3x8', 'Straight bar dips 3x12'] },
      { id: 'mu_strict', name: 'Strict muscle-up', type: 'reps', goal: '3x3, no swing', target: { sets: 3, value: 3 },
        how: 'Dead hang start, false grip optional, pull high and lean over bar.',
        drills: ['High pull-ups to waist 3x5', 'Transition negatives 3x3'] },
      { id: 'mu_ring', name: 'Explosive muscle-up (bar to hips)', type: 'reps', goal: '3x5, bar reaches the hips', target: { sets: 3, value: 5 },
          how: 'Pull so hard the bar reaches your hips, then press out. Builds the height you need for clap and 360.',
          drills: ['Explosive pull-ups to waist 3x4', 'Straight bar dips 3x12'] },
      { id: 'mu_slow', name: 'Slow muscle-up', type: 'reps', goal: '3x2 (5 s pull, 3 s transition)', target: { sets: 3, value: 2 },
        how: 'No momentum, smooth transition by leaning chest forward.',
        drills: ['Strict MU negatives 3x3', 'Weighted chest-to-bar 3x5'] },
      { id: 'mu_weighted', name: 'Muscle-up volume', type: 'reps', goal: '3x10 clean', target: { sets: 3, value: 10 },
          how: 'Ten clean reps per set, same bar path every rep. Volume before the dynamic variations.',
          drills: ['Chest-to-bar pull-ups 3x10', 'Straight bar dips 3x15'] },
      { id: 'mu_clap', name: 'Clap muscle-up', type: 'reps', goal: '3x3', target: { sets: 3, value: 3 },
        how: 'Explode above bar, release, clap, regrip before descent. Use a padded bar first.',
        drills: ['Explosive MU with hand release 3x3', 'Plyo pull-ups 3x5'] },
      { id: 'mu_360', name: '360 muscle-up', type: 'reps', goal: '3x1 landed', target: { sets: 3, value: 1 },
        how: 'Max height, rotate with head and shoulders, catch bar in support. Learn with a spotter.',
        drills: ['180 muscle-up 3x2', 'Clap MU 3x3'] }
    ] },

  { key: 'human_flag', name: 'Human flag', family: 'core',
    why: 'Builds lateral chain strength, oblique and shoulder stability in a press-pull position.',
    prereq: 'Side plank 60 s each and 10+ pull-ups.',
    steps: [
      { id: 'flag_vertical', name: 'Vertical flag', type: 'time', goal: '3x15 s each side', target: { sets: 3, value: 15 },
        how: 'Bottom arm pushes, top arm pulls, body vertical and straight.',
        drills: ['Side plank 3x45 s', 'Hanging oblique raises 3x8'] },
      { id: 'flag_tuck', name: 'Tuck flag', type: 'time', goal: '3x10 s each side', target: { sets: 3, value: 10 },
        how: 'Knees to chest, hips stacked over bottom hand, push hard through lower arm.',
        drills: ['Flag negatives from vertical 3x3', 'Lateral raises 3x12'] },
      { id: 'flag_straddle', name: 'Straddle flag', type: 'time', goal: '3x8 s each side', target: { sets: 3, value: 8 },
        how: 'Wide legs, hips level, top shoulder depressed.',
        drills: ['One-leg flag 3x8 s', 'Copenhagen plank 3x20 s'] },
      { id: 'flag_full', name: 'Full human flag', type: 'time', goal: '3x5 s each side', target: { sets: 3, value: 5 },
        how: 'Legs together, body horizontal, no hip sag.',
        drills: ['Straddle flag 4x6 s', 'Flag raises from vertical 3x3'] },
      { id: 'flag_long', name: 'Full flag 10 s', type: 'time', goal: '3x10 s each side', target: { sets: 3, value: 10 },
        how: 'Consistent line both sides, entry without kick.',
        drills: ['Flag raises 3x3', 'Flag holds on weak side 2x extra set'] },
      { id: 'flag_raises', name: 'Human flag raises', type: 'reps', goal: '3x3 each side', target: { sets: 3, value: 3 },
        how: 'From vertical, lower to horizontal and raise back with straight body.',
        drills: ['Flag negatives 3x3', 'Windmills on pole 3x3'] }
    ] },

  { key: 'vsit_manna', name: 'V-sit and manna', family: 'core',
    why: 'Builds compression strength, hip flexor and shoulder extension needed for presses and freestyle.',
    prereq: 'L-sit 20 s and solid pike flexibility (palms to floor).',
    steps: [
      { id: 'vm_lsit', name: 'L-sit', type: 'time', goal: '3x30 s', target: { sets: 3, value: 30 },
        how: 'Locked elbows, shoulders depressed, legs straight and pointed.',
        drills: ['Seated pike leg lifts 3x12', 'Support hold 3x30 s'] },
      { id: 'vm_straddle_l', name: 'Straddle L-sit (high)', type: 'time', goal: '3x15 s', target: { sets: 3, value: 15 },
        how: 'Hands between legs, lift hips back, legs above floor level.',
        drills: ['Pancake compression lifts 3x10', 'Pancake stretch 3x60 s'] },
      { id: 'vm_vsit_45', name: 'V-sit 45 deg', type: 'time', goal: '3x10 s', target: { sets: 3, value: 10 },
        how: 'Lean back slightly, push hands forward, pull legs toward face.',
        drills: ['Pike compression pulses 3x15', 'Hanging pike raises 3x8'] },
      { id: 'vm_vsit', name: 'Full V-sit', type: 'time', goal: '3x10 s, legs near vertical', target: { sets: 3, value: 10 },
        how: 'Hips forward of hands, shoulders behind, legs past vertical toward face.',
        drills: ['Elevated V-sit raises 3x5', 'Shoulder extension stretch 3x45 s'] },
      { id: 'vm_manna_prep', name: 'Manna prep (hips lifted, hands behind)', type: 'time', goal: '3x10 s, hips off floor', target: { sets: 3, value: 10 },
        how: 'Fingers back, elbows locked, push hips up and back past hands.',
        drills: ['Reverse support lifts 3x8', 'Hand-behind shoulder extension holds 3x30 s'] },
      { id: 'vm_manna_tuck', name: 'Elevated manna attempt', type: 'time', goal: '5x3 s with feet passing hands', target: { sets: 5, value: 3 },
        how: 'On parallettes, extend hips backward with legs straight, maximal compression.',
        drills: ['Assisted manna with band 3x5 s', 'Seated compression holds 3x20 s'] }
    ] },

  { key: 'dragon_flag', name: 'Dragon flag and core', family: 'core',
    why: 'Builds anti-extension core strength that supports levers, planche line and handstand stability.',
    prereq: 'Hollow body hold 60 s and 10 hanging leg raises.',
    steps: [
      { id: 'df_tuck', name: 'Tuck dragon flag negatives', type: 'reps', goal: '3x6 (5 s down)', target: { sets: 3, value: 6 },
        how: 'Shoulders on bench, hips extended, lower slowly with knees tucked.',
        drills: ['Hollow rocks 3x20', 'Reverse crunches 3x12'] },
      { id: 'df_straddle', name: 'Straddle dragon flag', type: 'reps', goal: '3x5', target: { sets: 3, value: 5 },
        how: 'Keep hips straight, do not pike at the bottom.',
        drills: ['Straddle DF holds 3x10 s', 'Ab wheel rollouts 3x8'] },
      { id: 'df_full', name: 'Full dragon flag', type: 'reps', goal: '3x5 slow', target: { sets: 3, value: 5 },
        how: 'Legs together, body rigid from shoulders to toes, 3 s down, 2 s up.',
        drills: ['Full DF hold 3x10 s', 'Standing ab wheel negatives 3x3'] },
      { id: 'df_toes_to_bar', name: 'Strict toes-to-bar', type: 'reps', goal: '3x12', target: { sets: 3, value: 12 },
        how: 'No swing, straight legs, posterior pelvic tilt at the top.',
        drills: ['Hanging L-sit 3x15 s', 'Pike compression lifts 3x10'] },
      { id: 'df_wheel', name: 'Standing ab wheel rollout', type: 'reps', goal: '3x5', target: { sets: 3, value: 5 },
        how: 'Hollow body, roll out fully, return without hip pike.',
        drills: ['Kneeling rollouts 3x12', 'Wall-assisted standing rollouts 3x5'] },
      { id: 'df_weighted', name: 'Dragon flag hold', type: 'time', goal: '3x10 s, body straight', target: { sets: 3, value: 10 },
          how: 'Hold the straight line halfway down. Stop if the lower back arches.',
          drills: ['Hanging windshield wipers 3x8', 'Front lever raises 3x5'] }
    ] },

  { key: 'freestyle_bar', name: 'Bar freestyle', family: 'dynamic',
    why: 'Swings, circles and releases on the bar: the moves freestyle competitions are judged on.',
    prereq: '8+ clean muscle-ups and solid grip.',
    steps: [
      { id: 'fs_tap_swing', name: 'Tap swing', type: 'reps', goal: '3x10 controlled swings', target: { sets: 3, value: 10 },
        how: 'Hollow to arch from the shoulders, legs together. The base of every swing move.',
        drills: ['Active hang 3x30 s', 'Hollow body rocks 3x15'] },
      { id: 'fs_pullover', name: 'Pullover', type: 'reps', goal: '3x5', target: { sets: 3, value: 5 },
        how: 'Pull the hips to the bar and roll over it into front support.',
        drills: ['Hanging knee raises to the bar 3x8', 'Front support hold 3x20 s'] },
      { id: 'fs_hip_circle', name: 'Back hip circle', type: 'reps', goal: '3x5 from support', target: { sets: 3, value: 5 },
        how: 'From front support, drop the shoulders back and circle the bar with the hips glued to it.',
        drills: ['Pullovers 3x5', 'Wrist curls 3x15'] },
      { id: 'fs_under_bar', name: 'Under bar', type: 'reps', goal: '3x3 to front support', target: { sets: 3, value: 3 },
        how: 'Swing the feet under the bar and shoot forward, landing in support on the other side.',
        drills: ['Tap swings 3x10', 'Explosive pull-ups 3x4'] },
      { id: 'fs_180_mu', name: '180 muscle-up', type: 'reps', goal: '3x3', target: { sets: 3, value: 3 },
        how: 'Explosive muscle-up, release at the top and turn 180 degrees to catch the bar facing the other way.',
        drills: ['Explosive muscle-ups 3x5', 'Clap pull-ups 3x3'] },
      { id: 'fs_around_world', name: 'Around the world', type: 'reps', goal: '3x2', target: { sets: 3, value: 2 },
        how: 'Muscle-up while travelling around one hand, landing sideways over the bar.',
        drills: ['Explosive muscle-ups 3x5', 'Archer pull-ups 3x5'] },
      { id: 'fs_swing_360', name: 'Swing 360', type: 'reps', goal: '3x1 caught', target: { sets: 3, value: 1 },
        how: 'From a big tap swing, release at the top of the front swing, turn 360 and regrip. Learn over a soft mat.',
        drills: ['Swing 180 regrips 3x3', 'Tap swings 3x10'] }
    ] },

  { key: 'one_arm_pushup', name: 'One-arm push-up', family: 'push',
    why: 'Single-arm pushing strength and anti-rotation core, a classic strength standard.',
    prereq: '30 strict push-ups.',
    steps: [
      { id: 'oapu_archer', name: 'Archer push-up', type: 'reps', goal: '3x8 each side', target: { sets: 3, value: 8 },
        how: 'Working arm bent, other arm straight out to the side for support.',
        drills: ['Diamond push-ups 3x15', 'Plank 3x45 s'] },
      { id: 'oapu_incline', name: 'Incline one-arm push-up', type: 'reps', goal: '3x6 each, hands on a bench', target: { sets: 3, value: 6 },
        how: 'Feet wide, hips square, chest to the bench.',
        drills: ['Archer push-ups 3x8', 'Side plank 3x30 s'] },
      { id: 'oapu_neg', name: 'One-arm push-up negatives', type: 'reps', goal: '3x3 each, 5 s down', target: { sets: 3, value: 3 },
        how: 'Lower slowly on one arm, push back up with two.',
        drills: ['Incline one-arm push-ups 3x6', 'Pseudo planche push-ups 3x8'] },
      { id: 'oapu_full', name: 'One-arm push-up', type: 'reps', goal: '3x3 each side', target: { sets: 3, value: 3 },
        how: 'Feet wide, elbow tucked, no hip twist.',
        drills: ['Negatives 3x3', 'Archer push-ups 3x10'] },
      { id: 'oapu_feet_close', name: 'One-arm push-up, feet together', type: 'reps', goal: '3x5 each side', target: { sets: 3, value: 5 },
        how: 'Feet together makes the anti-rotation much harder. Stay square.',
        drills: ['One-arm push-ups 3x5', 'Side plank 3x45 s'] }
    ] },

  { key: 'elbow_lever', name: 'Elbow lever and crane', family: 'balance',
    why: 'Arm balances that build wrist strength and control for floor freestyle.',
    prereq: 'Wrist prep and a 30 s plank.',
    steps: [
      { id: 'el_crow', name: 'Crow pose', type: 'time', goal: '3x30 s', target: { sets: 3, value: 30 },
        how: 'Knees on the back of the arms, lean forward until the feet float.',
        drills: ['Wrist prep circuit', 'Frog stand rocks 3x10'] },
      { id: 'el_lever', name: 'Elbow lever', type: 'time', goal: '3x20 s', target: { sets: 3, value: 20 },
        how: 'Elbows into the hips, lean forward, body straight and level.',
        drills: ['Crow pose 3x30 s', 'Planche leans 3x20 s'] },
      { id: 'el_crane', name: 'Crane', type: 'time', goal: '3x15 s', target: { sets: 3, value: 15 },
        how: 'Crow with straight arms. Push the floor away.',
        drills: ['Crow pose 3x30 s', 'Pseudo planche push-ups 3x8'] },
      { id: 'el_one_arm', name: 'One-arm elbow lever', type: 'time', goal: '3x10 s each side', target: { sets: 3, value: 10 },
        how: 'Shift onto one elbow, free hand floats beside you.',
        drills: ['Elbow lever 3x20 s', 'Side plank 3x30 s'] }
    ] },

  { key: 'pistol', name: 'Pistol and shrimp squat', family: 'legs',
    why: 'Single-leg strength, balance and mobility: the calisthenics leg standards.',
    prereq: '20 deep bodyweight squats and decent ankle mobility.',
    steps: [
      { id: 'ps_box', name: 'Box pistol squat', type: 'reps', goal: '3x8 each leg', target: { sets: 3, value: 8 },
        how: 'Sit to a box on one leg, other leg straight out, stand back up.',
        drills: ['Knee-to-wall ankle mobility 2x12', 'Bulgarian split squats 3x10'] },
      { id: 'ps_assisted', name: 'Assisted pistol squat', type: 'reps', goal: '3x6 each, holding a post', target: { sets: 3, value: 6 },
        how: 'Full depth, use the post only for balance.',
        drills: ['Box pistols 3x8', 'Deep squat hold 3x60 s'] },
      { id: 'ps_pistol', name: 'Pistol squat', type: 'reps', goal: '3x5 each leg', target: { sets: 3, value: 5 },
        how: 'Arms forward as a counterweight, heel down, slow on the way down.',
        drills: ['Assisted pistols 3x6', 'Tibialis raises 2x20'] },
      { id: 'ps_shrimp', name: 'Shrimp squat', type: 'reps', goal: '3x5 each leg', target: { sets: 3, value: 5 },
        how: 'Hold the back foot, lower until the back knee touches the floor.',
        drills: ['Reverse lunges 3x10', 'Couch stretch 2x60 s'] },
      { id: 'ps_dragon', name: 'Dragon pistol squat', type: 'reps', goal: '3x3 each leg', target: { sets: 3, value: 3 },
        how: 'Free leg passes behind the working leg. Needs strength and hip mobility.',
        drills: ['Pistols 3x5', '90/90 hip switches 2x10'] }
    ] }
];

const ATHLETE_GUIDE = {
  nutrition: [
    { title: 'Cut vs performance phases',
      body: 'Maintenance is roughly 2500-2700 kcal at 63 kg training 6 days. Cut at 300-500 kcal below (about 2100) for 6-10 weeks max, losing 0.5-0.7% bodyweight per week, then run maintenance or a small surplus while chasing hard skills.' },
    { title: 'Protein target',
      body: 'ISSN suggests 1.6-2.2 g/kg normally and 2.3-3.1 g/kg of lean mass during a cut. For you: 140-160 g on a cut, 120-140 g at maintenance. Spread over 4 meals of 30-40 g.' },
    { title: 'Carbs around training',
      body: 'Carbs fuel quality skill work. Aim for 3-5 g/kg (190-300 g), placing most of them in the pre- and post-training meals. Keep low-carb days for rest days if needed.' },
    { title: 'Fats and micronutrients',
      body: 'Keep fat at 0.8-1 g/kg (50-65 g) for hormones. Prioritise oily fish, eggs, olive oil and nuts. Eat fruit and vegetables daily; vitamin D and omega-3 are useful for tendon and joint health.' },
    { title: 'Hydration and creatine',
      body: 'Drink 35-45 ml/kg (about 2.5-3 L) plus sweat losses, with salt on heavy days. Creatine monohydrate 3-5 g daily is safe and well supported; expect 1-2 kg water weight early.' },
    { title: 'Power-to-weight',
      body: 'Lighter bodyweight makes levers and planche easier, but deep deficits kill strength and tendon recovery. Aim for about 10-12% body fat, not stage-lean. Do not cut while peaking a new skill.' },
    { title: 'Sample day: 2100 kcal / 135 g protein',
      body: 'Breakfast: 3 eggs, oats 60 g, berries. Lunch: 150 g chicken, 200 g rice, veg. Pre-workout: banana, Greek yogurt 200 g. Dinner: 150 g salmon, potatoes 250 g, salad, olive oil. Snack: whey shake.' },
    { title: 'Meal timing',
      body: 'Eat a carb plus protein meal 2-3 h before training, or a light snack 60 min before. Have 30-40 g protein within a few hours after. A casein or cottage cheese snack before bed helps recovery.' }
  ],
  posture: [
    { title: 'Why shoulders round',
      body: 'Lots of pressing and isolation work plus sitting tightens the chest and front delts, while the mid-back and rotator cuff get weak. The shoulders get pulled forward and the head follows.' },
    { title: 'The fix, built into your plan',
      body: 'Every warm-up now has band pull-aparts and wall slides. Leg days add Y-T-W raises or external rotations. Sunday adds pec stretches and chin tucks. Face pulls and rear delt flies stay twice a week.' },
    { title: 'Pull more than you push',
      body: 'Aim for about 1.5 pulling sets for every pressing set until posture improves. When short on time, never skip face pulls, rows or rear delts.' },
    { title: 'Daily 5-minute habit',
      body: '20 band pull-aparts, 10 wall slides, 10 chin tucks and a 45 s doorway pec stretch each side. Do it at your desk too. Posture changes come from daily frequency, not one hard session.' },
    { title: 'Check it monthly',
      body: 'Take a side-on photo, relaxed, on the 1st of each month. Your ear should drift back over the shoulder and your knuckles should face more to the side than the front.' }
  ],
  recovery: [
    { title: 'Sleep',
      body: 'Aim for 7.5-9 h with a consistent schedule. Sleep is when tendons and the nervous system recover; poor sleep is the fastest way to stall straight-arm strength and lose muscle on a cut.' },
    { title: 'Deloads',
      body: 'Every 4th week, or after 3 hard weeks, cut volume by 40-50% and keep intensity moderate. Deload sooner if joints ache, performance drops two sessions in a row, or motivation crashes.' },
    { title: 'Tendons and connective tissue',
      body: 'Straight-arm work stresses biceps tendons, elbows and wrists, which adapt slower than muscle. Add volume gradually (max about 10% per week), warm up wrists and elbows, and do light high-rep curls and wrist work.' },
    { title: 'Mobility',
      body: 'Daily 10-15 min: wrist extension, shoulder flexion for handstands, shoulder extension for back lever and manna, pike and pancake for presses and V-sit. Mobility unlocks positions strength cannot.' },
    { title: 'Injury warning signs',
      body: 'Stop the skill if you feel sharp elbow pain (inner or front), wrist pain under load, pain lasting more than 48 h, or night pain. Back off load, train pain-free variants and see a physio if it persists.' }
  ],
  training: [
    { title: 'Building muscle in the gym',
      body: 'Gym exercises (marked Muscle) build size. Stop each set with 1-2 reps left. When you hit the top of the rep range on every set, add the smallest weight step. Rest 1-2 min. Muscle needs food: eat near 2,400 kcal.' },
    { title: 'Skill work first, fresh and short',
      body: 'Do hardest skills first after warm-up. Use low reps or short holds at high quality, 2-3 min rest between sets. End the set when form breaks. Strength accessories come after.' },
    { title: 'Frequency and focus',
      body: 'Train each main skill 2-3 times per week. Focus on 2-3 primary skills at once (one push, one pull, one balance), keeping others on maintenance with one short session weekly.' },
    { title: 'Progression criteria',
      body: 'Move up when you hit the step goal with clean form on two separate sessions. Holds: aim for 3x10-15 s before the next lever. Reps: hit the target sets x reps without kipping.' },
    { title: 'Periodization',
      body: 'Run 3 hard weeks then 1 deload. Rotate emphasis each block: e.g. planche and FL heavy, then HSPU and OAP heavy. Keep 6-day PPL but place skills on matching days.' },
    { title: 'Professional path',
      body: 'Choose statics (planche, FL, combos, judged holds) or freestyle (dynamics, bar flow). Compete in local and national events (WSWCF, Battle of the Bars, SWUAG) and build a social channel showing consistent progress and combos.' },
    { title: 'Combine strength and skill',
      body: 'Elite skills need base strength: weighted dips and pull-ups (+40-50% BW), heavy rows, ring support work. Pair each skill with 1-2 strength accessories to build the tendon and muscle capacity.' }
  ]
};


// Where this athlete starts on each ladder, and which fixed program slots a focused skill replaces.
const SKILL_SETUP = {
  front_lever:    { start: 3, replaces: ['fl_straddle', 'fl_raise', 'fl_neg', 'fl_tuck'] },
  planche:        { start: 4, replaces: ['planche_str', 'planche_tpu', 'planche_lean'] },
  hspu:           { start: 1, replaces: ['pike_pu', 'hspu_neg', 'hspu'] },
  oahs_press:     { start: 0, replaces: ['handstand'] },
  back_lever:     { start: 2, replaces: ['back_lever'] },
  muscle_up_adv:  { start: 1, replaces: ['muscle_up', 'mu_slow'] },
  vsit_manna:     { start: 0, replaces: ['lsit'] },
  dragon_flag:    { start: 0, replaces: ['dragon_flag'] },
  freestyle_bar:  { start: 0 },
  one_arm_pushup: { start: 0, replaces: ['archer_pu'] },
  elbow_lever:    { start: 0 },
  pistol:         { start: 0 },
};
for (const t of SKILL_TREES) Object.assign(t, SKILL_SETUP[t.key] || {});

// One or two skills every day: push skills Mon/Thu, pull Tue/Fri, handstand + L-sit Wed/Sat, light handstand Sunday.
const DEFAULT_FOCUS = ['planche', 'hspu', 'front_lever', 'muscle_up_adv', 'oahs_press', 'vsit_manna'];
const MAX_FOCUS = 6;
